[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  command = "npx pnpm install=node_modules/.pnpm-store && npx pnpm run dev -o"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200